apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespage: stock
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: h2s2l/gateway:v2
          ports:
            - containerPort: 8080